#!/bin/bash

TIMESTAMP=`date +%Y%m%d%H%M`

SERVICESHOME=~/Projects/Services
LOGFILE=${SERVICESHOME}/logs/weather_service_${TIMESTAMP}.log
LOGGINGLEVEL="INFO"
TEMPERATURELOGFILE=${SERVICESHOME}/logs/temperatures_${TIMESTAMP}.csv
OUTTOPIC="services.xbee.sensor_readings"
MESSAGEQUEUETOPIC="services.xbee.packet"
MESSAGEQUEUEADDRESS="127.0.0.1"
MESSAGEQUEUEPORT=5250

source ${SERVICESHOME}/testbed/bin/activate

python ${SERVICESHOME}/src/WeatherServiceTester.py \
	--logFile ${LOGFILE} \
	--loggingLevel ${LOGGINGLEVEL} \
	--temperatureLogFile ${TEMPERATURELOGFILE} \
	--messageQueueTopic ${MESSAGEQUEUETOPIC} \
	--messageQueueAddress ${MESSAGEQUEUEADDRESS} \
	--messageQueuePort ${MESSAGEQUEUEPORT} \
	--outTopic ${OUTTOPIC} &

